language: node_js
node_js:
  - 12.16.1
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: github
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
